# docker-compose build && docker-compose up -d

version: '3.7'
services:

#  backend:
#      build: .
#      container_name: digitalmaps_backend
#      image: "django-rest-api_web:latest"
#      env_file:
#        - ./environment.env
#      network_mode: "host"
#      depends_on:
#        - postgres
#      ports:
#        - "8001:8001"
#      expose:
#        - 8001
#      networks:
#        - prisma_network
#      command: bash -c "daphne prisma.asgi:application --bind 0.0.0.0 --port 8001 -v2 --websocket_connect_timeout 10800"

  postgres:
      build: ./postgres
      container_name: digitalmaps_postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      expose:
        - 5432
      network_mode: "host"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: magalu
        POSTGRES_DB: digitalmaps
        PGDATA: /data/postgres
      volumes:
        - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  media:
  static: